# Dependencies
markdown:         kramdown
# highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            '向风车冲锋！'
tagline:          'VITURES'
description:      '京华老宋体测试'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'JiaYi Zhang'
  url:            https://github.com/itzMeerkat

paginate:         5

# Custom vars
version:          0.0.2


plugins: [jekyll-paginate]