# Dependencies
markdown:         kramdown
# highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            '土拨鼠洞'
# tagline:          'VITURES'
description:      '生活没有答案，因为根本没有问题。'
url:              https://blog.jiayizhang.me
# baseurl:          /

author:
  name:           'JiaYi Zhang'
  url:            https://github.com/itzMeerkat

paginate:         10

# Custom vars
version:          0.0.2


plugins: [jekyll-paginate]

exclude: ['scripts', 'raw_fonts']